### ISSUE TITLE
Productive Bee compat causes server connection issues

### ISSUE THREAD

**Issue by JaisDK** [DivineRPG/DivineRPG-Compat#2]
This line needs to say `"productivebees:rupee"` instead of `"divinerpg:raw_rupee"`. The same change is needed for the other bees.
https://github.com/DivineRPG/DivineRPG-Compat/blob/1.20/src/main/resources/data/productivebees/recipes/bee_produce/rupee_bee.json#L3

![image](https://github.com/DivineRPG/DivineRPG-Compat/assets/15868585/d5d928d3-eab3-40bb-a9dd-797bbc49d4b1)

**Comment by NicosaurusRex99** [comment]
Thanks for the report :)
